language: cpp
sudo: required

compiler:
  - clang
  - gcc
os:
  - linux
  - osx

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler libprotobuf-dev

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TEST=ON .. && make
  - ctest
