dist: trusty
sudo: false
language: cpp

addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - protobuf-compiler
    - libprotobuf-dev

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TEST=ON .. && make
  - ctest
